# Generated by Django 6.0.5 on 2026-05-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='notify_by_email',
            field=models.BooleanField(default=True, verbose_name='оповещения по email'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_by_telegram',
            field=models.BooleanField(default=False, verbose_name='оповещения в Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='public_display_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='отображаемое имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Telegram chat id'),
        ),
    ]
