# Generated by Django 6.0.5 on 2026-05-26 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_notify_by_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='код')),
                ('expires_at', models.DateTimeField(verbose_name='истекает')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_codes', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'код привязки Telegram',
                'verbose_name_plural': 'коды привязки Telegram',
                'ordering': ('-created_at',),
            },
        ),
    ]
