# Generated by Django 6.0.5 on 2026-05-26 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время')),
                ('action', models.CharField(max_length=255, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='приятная')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, verbose_name='периодичность (дней)')),
                ('reward', models.CharField(blank=True, default='', max_length=255, verbose_name='награда')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='длительность (сек)')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичная')),
                ('last_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='последнее напоминание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлена')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_useful_habits', to='habits.habit', verbose_name='связанная приятная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': ('-created_at',),
            },
        ),
    ]
