# Generated by Django 6.0.5 on 2026-05-26 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время')),
                ('action', models.CharField(max_length=255, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='приятная')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, verbose_name='периодичность (дней)')),
                ('reward', models.CharField(blank=True, default='', max_length=255, verbose_name='награда')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='длительность (сек)')),
                ('category', models.CharField(choices=[('health', 'здоровье'), ('focus', 'фокус'), ('calm', 'спокойствие'), ('home', 'дом'), ('social', 'общение'), ('learning', 'обучение')], default='health', max_length=32, verbose_name='категория')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='slug')),
                ('tagline', models.CharField(blank=True, default='', max_length=119, verbose_name='подпись')),
                ('pair_group', models.SlugField(blank=True, default='', max_length=64, verbose_name='группа пары')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('is_featured', models.BooleanField(default=False, verbose_name='рекомендуем')),
                ('suggested_related_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_useful_templates', to='habits.habittemplate', verbose_name='рекомендуемая приятная')),
            ],
            options={
                'verbose_name': 'шаблон привычки',
                'verbose_name_plural': 'шаблоны привычек',
                'ordering': ('sort_order', 'slug'),
            },
        ),
    ]
