"""Данные каталога шаблонов для миграции seed (13 pleasant + 16 useful)."""

from __future__ import annotations

from typing import Any

PLEASANT_TEMPLATES: list[dict[str, Any]] = [
    {
        "slug": "reward-lemon-water",
        "action": "Выпить стакан воды с лимоном",
        "place": "Кухня",
        "time": "08:00",
        "duration": 30,
        "sort_order": 1,
        "tagline": "Лёгкий ритуал после движения",
    },
    {
        "slug": "reward-candle",
        "action": "Зажечь аромасвечу на 1 мин",
        "place": "Гостиная",
        "time": "22:05",
        "duration": 20,
        "sort_order": 2,
        "tagline": "Мягкий сигнал конца дня",
    },
    {
        "slug": "reward-track",
        "action": "Включить один любимый трек",
        "place": "Комната",
        "time": "08:10",
        "duration": 10,
        "sort_order": 3,
        "tagline": "Музыка как мгновенная награда",
    },
    {
        "slug": "reward-water-sip",
        "action": "Сделать осознанный глоток воды",
        "place": "Рабочий стол",
        "time": "12:05",
        "duration": 5,
        "sort_order": 4,
        "tagline": "Пауза без отвлечений",
    },
    {
        "slug": "reward-herbal-tea",
        "action": "Заварить чашку травяного чая",
        "place": "Кухня",
        "time": "21:50",
        "duration": 60,
        "sort_order": 5,
        "tagline": "Тепло после рефлексии",
    },
    {
        "slug": "reward-dark-chocolate",
        "action": "Съесть кусочек тёмного шоколада",
        "place": "Кухня",
        "time": "06:50",
        "duration": 30,
        "sort_order": 6,
        "tagline": "Сладкая точка после тишины",
    },
    {
        "slug": "reward-warm-shower",
        "action": "Тёплый душ 2 минуты",
        "place": "Ванная",
        "time": "19:35",
        "duration": 120,
        "sort_order": 7,
        "tagline": "Сброс дня за две минуты",
    },
    {
        "slug": "reward-mint-tea",
        "action": "Выпить мятный чай",
        "place": "Ванная",
        "time": "22:20",
        "duration": 45,
        "sort_order": 8,
        "tagline": "Свежесть после гигиены",
    },
    {
        "slug": "reward-window",
        "action": "30 с у окна без телефона",
        "place": "Окно",
        "time": "11:35",
        "duration": 30,
        "sort_order": 9,
        "tagline": "Короткий перезагруз мозга",
    },
    {
        "slug": "reward-stretch-arms",
        "action": "Потянуться всем телом",
        "place": "Спальня",
        "time": "07:05",
        "duration": 20,
        "sort_order": 10,
        "tagline": "Тело просыпается вместе с вами",
    },
    {
        "slug": "reward-desk-lamp",
        "action": "Включить мягкий свет на столе",
        "place": "Кабинет",
        "time": "21:05",
        "duration": 10,
        "sort_order": 11,
        "tagline": "Свет как якорь планирования",
    },
    {
        "slug": "reward-smile",
        "action": "Улыбнуться себе в зеркало",
        "place": "Прихожая",
        "time": "18:00",
        "duration": 5,
        "sort_order": 12,
        "tagline": "Микро-доза доброты к себе",
    },
    {
        "slug": "reward-phone-bed",
        "action": "Положить телефон на тумбочку вне кровати",
        "place": "Спальня",
        "time": "23:50",
        "duration": 15,
        "sort_order": 13,
        "tagline": "Сон начинается с одного жеста",
    },
]

USEFUL_TEMPLATES: list[dict[str, Any]] = [
    {
        "slug": "morning-hydrate",
        "pair_group": "morning-hydrate",
        "action": "Выпить полстакана воды после пробуждения",
        "time": "07:00",
        "place": "Кухня",
        "periodicity": 1,
        "duration": 30,
        "category": "health",
        "related_slug": "reward-stretch-arms",
        "sort_order": 20,
        "is_featured": True,
        "tagline": "Гидратация — первый якорь утра",
    },
    {
        "slug": "morning-move",
        "pair_group": "morning-move",
        "action": "Сделать 10 приседаний",
        "time": "07:25",
        "place": "Спальня",
        "periodicity": 1,
        "duration": 60,
        "category": "health",
        "related_slug": "reward-lemon-water",
        "sort_order": 21,
        "tagline": "Движение до завтрака",
    },
    {
        "slug": "morning-calm",
        "pair_group": "morning-calm",
        "action": "Медитировать 1 мин с закрытыми глазами",
        "time": "06:45",
        "place": "Уголок без экранов",
        "periodicity": 1,
        "duration": 60,
        "category": "calm",
        "reward": "Кусочек тёмного шоколада",
        "sort_order": 22,
        "tagline": "Тишина перед шумом дня",
    },
    {
        "slug": "evening-gratitude",
        "pair_group": "evening-gratitude",
        "action": "Записать 3 благодарности за день",
        "time": "21:45",
        "place": "Стол",
        "periodicity": 1,
        "duration": 90,
        "category": "calm",
        "related_slug": "reward-herbal-tea",
        "sort_order": 23,
        "tagline": "Закрыть день с благодарностью",
    },
    {
        "slug": "evening-read",
        "pair_group": "evening-read",
        "action": "Прочитать 2 страницы книги",
        "time": "22:00",
        "place": "Кресло у лампы",
        "periodicity": 1,
        "duration": 120,
        "category": "learning",
        "related_slug": "reward-candle",
        "sort_order": 24,
        "is_featured": True,
        "tagline": "Две страницы — уже победа",
    },
    {
        "slug": "morning-core",
        "pair_group": "morning-core",
        "action": "Планка 1 минута",
        "time": "08:00",
        "place": "Гостиная",
        "periodicity": 2,
        "duration": 60,
        "category": "health",
        "related_slug": "reward-track",
        "sort_order": 25,
        "tagline": "Сила кора за минуту",
    },
    {
        "slug": "home-plant",
        "pair_group": "home-plant",
        "action": "Полить одно комнатное растение",
        "time": "09:00",
        "place": "Подоконник",
        "periodicity": 3,
        "duration": 30,
        "category": "home",
        "reward": "Чашка кофе",
        "sort_order": 26,
        "tagline": "Забота о зелёном соседе",
    },
    {
        "slug": "work-posture",
        "pair_group": "work-posture",
        "action": "Выпрямить спину, опустить плечи",
        "time": "12:00",
        "place": "Рабочее место",
        "periodicity": 1,
        "duration": 10,
        "category": "focus",
        "related_slug": "reward-water-sip",
        "sort_order": 27,
        "tagline": "Осанка как якорь фокуса",
    },
    {
        "slug": "evening-walk",
        "pair_group": "evening-walk",
        "action": "Прогуляться 2 минуты рядом с домом",
        "time": "19:30",
        "place": "Улица у дома",
        "periodicity": 1,
        "duration": 120,
        "category": "health",
        "related_slug": "reward-warm-shower",
        "sort_order": 28,
        "is_featured": True,
        "tagline": "Короткая прогулка — уже победа",
    },
    {
        "slug": "work-breath",
        "pair_group": "work-breath",
        "action": "10 медленных вдохов-выдохов",
        "time": "15:00",
        "place": "Офис",
        "periodicity": 1,
        "duration": 45,
        "category": "focus",
        "reward": "5 минут паузы",
        "sort_order": 29,
        "tagline": "Дыхание возвращает внимание",
    },
    {
        "slug": "evening-floss",
        "pair_group": "evening-floss",
        "action": "Зубная нить 30 секунд",
        "time": "22:15",
        "place": "Ванная",
        "periodicity": 1,
        "duration": 45,
        "category": "health",
        "related_slug": "reward-mint-tea",
        "sort_order": 30,
        "tagline": "Гигиена без отговорок",
    },
    {
        "slug": "work-desk",
        "pair_group": "work-desk",
        "action": "Убрать 3 предмета со стола",
        "time": "17:50",
        "place": "Стол",
        "periodicity": 1,
        "duration": 60,
        "category": "focus",
        "related_slug": "reward-track",
        "sort_order": 31,
        "tagline": "Чистый стол — чистый фокус",
    },
    {
        "slug": "social-ping",
        "pair_group": "social-ping",
        "action": "Отправить тёплое сообщение близкому",
        "time": "19:00",
        "place": "Диван",
        "periodicity": 2,
        "duration": 60,
        "category": "social",
        "reward": "10 минут сериала",
        "sort_order": 32,
        "tagline": "Связь важнее идеального текста",
    },
    {
        "slug": "plan-tomorrow",
        "pair_group": "plan-tomorrow",
        "action": "Назвать 1 главную задачу на завтра",
        "time": "21:00",
        "place": "Стол",
        "periodicity": 1,
        "duration": 90,
        "category": "focus",
        "related_slug": "reward-desk-lamp",
        "sort_order": 33,
        "tagline": "Один приоритет лучше десяти",
    },
    {
        "slug": "midday-reset",
        "pair_group": "midday-reset",
        "action": "Размять шею и плечи 5+5 раз",
        "time": "11:30",
        "place": "Стул",
        "periodicity": 1,
        "duration": 40,
        "category": "health",
        "related_slug": "reward-window",
        "sort_order": 34,
        "tagline": "Тело благодарит за паузу",
    },
    {
        "slug": "sleep-before-midnight",
        "pair_group": "sleep-before-midnight",
        "action": "Лечь в кровать до 23:59",
        "time": "23:45",
        "place": "Спальня",
        "periodicity": 1,
        "duration": 60,
        "category": "calm",
        "related_slug": "reward-phone-bed",
        "sort_order": 35,
        "is_featured": True,
        "tagline": "Сон до полуночи начинается с одного жеста",
    },
]
